application: hunorkovacscom
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: hunorkovacscom/home.html
  upload: hunorkovacscom/home.html

- url: /githelp
  static_files: hunorkovacscom/githelp.txt
  upload: hunorkovacscom/githelp.txt

- url: /resume
  static_files: hunorkovacscom/resume.html
  upload: hunorkovacscom/resume.html

- url: /akkastreams
  script: _go_app

- url: /
  static_dir: hunorkovacscom/static

# - url: /.*
#  script: _go_app

skip_files:
- ^\.idea(/.*)?
- ^\.git(/.*)?
