runtime: go115

handlers:
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /
    static_files: home.html
    upload: home.html

  - url: /THEVASTATLANTIC
    static_files: thevastatlantic.html
    upload: thevastatlantic.html

  - url: /HUNORIIKOVACSPFA
    static_files: hunoriikovacspfa.html
    upload: hunoriikovacspfa.html

  - url: /error
    static_files: error.html
    upload: error.html

  - url: /40371A0ABB29EBF6A9A8AA1AB35209D6EF228B00
    static_files: static/40371A0ABB29EBF6A9A8AA1AB35209D6EF228B00
    upload: static/40371A0ABB29EBF6A9A8AA1AB35209D6EF228B00
    mime_type: text/plain

  - url: /static
    static_dir: static

  - url: /.*
    script: auto

error_handlers:
  - file: error.html
