runtime: go114

handlers:
  - url: /favicon\.ico
    static_files: /static/favicon.ico
    upload: favicon\.ico

  - url: /
    static_files: home.html
    upload: home.html

  - url: /
    static_dir: static

  - url: /somethingspecial123
    script: auto
