runtime: go114

handlers:
  - url: /favicon\.ico
    static_files: /static/favicon.ico
    upload: favicon\.ico

  - url: /
    static_files: home.html
    upload: home.html

  - url: /error
    static_files: error.html
    upload: error.html

  - url: /static
    static_dir: static

  - url: /.*
    script: auto

error_handlers:
  - file: error.html
